# GET all todos with status 'TO DO'
GET http://localhost:3000/todos/?status=TO%20DO

###

# GET all todos with priority 'HIGH'
GET http://localhost:3000/todos/?priority=HIGH

###

# GET all todos with priority 'HIGH' and status 'IN PROGRESS'
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

# GET all todos with category 'WORK' and status 'DONE'
GET http://localhost:3000/todos/?category=WORK&status=DONE

###

# GET all todos with category 'LEARNING' and priority 'HIGH'
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###

# GET all todos with category 'HOME'
GET http://localhost:3000/todos/?category=HOME

###

# GET all todos whose todo contains 'Buy'
GET http://localhost:3000/todos/?search_q=Buy

###

# GET a specific todo by ID
GET http://localhost:3000/todos/1

###

# GET all todos of a specific date
GET http://localhost:3000/agenda/?date=2021-01-21
